# Generated by Django 5.1.4 on 2024-12-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_foodgram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
    ]
