# Generated by Django 4.2.17 on 2025-01-16 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_foodgram', '0003_alter_shoppingcart_recipe_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('-id',), 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ('-id',), 'verbose_name': 'Рецепт-Ингредиент', 'verbose_name_plural': 'Рецепты-Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipeshortlink',
            options={'verbose_name': 'Рецепт-Короткая ссылка', 'verbose_name_plural': 'Рецепты-Короткие ссылки'},
        ),
        migrations.AlterModelOptions(
            name='recipetag',
            options={'verbose_name': 'Рецепт-Тег', 'verbose_name_plural': 'Рецепты-Теги'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ('-id',), 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
