# Generated by Django 5.1.4 on 2024-12-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_foodgram', '0003_alter_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ('-id',)},
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient', 'amount'), name='unique_recipeingredient_recipe_ingredient_amount'),
        ),
    ]
