# Generated by Django 5.1.4 on 2025-01-10 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_foodgram', '0003_recipe_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_link', models.CharField(max_length=4, unique=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fullrecipe', to='backend_foodgram.recipe')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recipe', 'short_link'), name='unique_recipeshortlink_recipe_shortlink')],
            },
        ),
    ]
